export const environment = {
  envVar: {
    GITLAB_APP_BASE_URI: '',
    GITLAB_API_BASE_URI: '',
    GITLAB_APP_ID: '',
    GITLAB_AUTH_REDIRECT_URI: '',
    GITLAB_ID_PROJET_REINTEGRATION: 0,
    GITLAB_ID_PROJET_SUIVI_GENERAL: 0,
    GITLAB_ID_PROJET_CORRECTIONS_DIVERSES: 0,
  },
};
